### ISSUE TITLE
index_cn.php

### ISSUE THREAD

**Issue by Suiyi-Light** [injahow/meting-api#1]
现在的好像获取不到中文词了
https://api.suiyil.cn/meting-api-master/index_cn.php?type=lrc&id=460099378
之前的可以
https://api.suiyil.cn/163-api/index_cn.php?type=lrc&id=460099378

**Comment by injahow** [comment]
感谢反馈，准备尝试修复。

**Comment by injahow** [comment]
> 现在的好像获取不到中文词了
> https://api.suiyil.cn/meting-api-master/index_cn.php?type=lrc&id=460099378
> 之前的可以
> https://api.suiyil.cn/163-api/index_cn.php?type=lrc&id=460099378

感谢反馈，准备尝试修复。
