### ISSUE TITLE
提示未知歌单

### ISSUE THREAD

**Issue by kcn3388** [injahow/meting-api#3]
如图
![image](https://user-images.githubusercontent.com/25716090/123512520-7d564900-d6ba-11eb-9651-5e67846c1c5c.png)

突然之间不行了，服务器是vultr的vps，是海外的

**Comment by injahow** [comment]
> 如图
> ![image](https://user-images.githubusercontent.com/25716090/123512520-7d564900-d6ba-11eb-9651-5e67846c1c5c.png)
> 
> 突然之间不行了，服务器是vultr的vps，是海外的

![image](https://user-images.githubusercontent.com/42839062/123512590-e63dc100-d6ba-11eb-8e9d-3619d539cd6d.png)
请确认id，type等参数的准确性

**Comment by kcn3388** [comment]
> > 如图
> > ![image](https://user-images.githubusercontent.com/25716090/123512520-7d564900-d6ba-11eb-9651-5e67846c1c5c.png)
> > 突然之间不行了，服务器是vultr的vps，是海外的
> 
> ![image](https://user-images.githubusercontent.com/42839062/123512590-e63dc100-d6ba-11eb-8e9d-3619d539cd6d.png)
> 请确认id，type等参数的准确性

已解决，cookie已过期，在源repo中有介绍
