### ISSUE TITLE
[功能增加请求] 发送request时header添加X-Real-IP

### ISSUE THREAD

**Issue by kcn3388** [injahow/meting-api#4]
原因如下，使用国外ip访问时会遭遇网易云的阻拦，另一api repo给出了解决方法。

https://github.com/Binaryify/NeteaseCloudMusicApi/issues/29#issuecomment-298358438

Update: 报错原因
海外解析播放服务器会强制解析至localhost。
![image](https://user-images.githubusercontent.com/25716090/123754768-d0641200-d8ed-11eb-8345-938421b51c33.png)
解决方法如下
https://fireattack.wordpress.com/2016/03/27/netease-music/
该解决方法只对当前客户端有效，希望可以在api处进行处理

**Comment by injahow** [comment]
![image](https://user-images.githubusercontent.com/42839062/123761330-4d928580-d8f4-11eb-8f6d-e563b9bd15e6.png)
Meting源码中已存在随机X-Real-IP，可否提供问题的具体详情

**Comment by kcn3388** [comment]
> ![image](https://user-images.githubusercontent.com/42839062/123761330-4d928580-d8f4-11eb-8f6d-e563b9bd15e6.png)
> Meting源码中已存在随机X-Real-IP，可否提供问题的具体详情

挂全局梯子的时候，会导致获取音乐链接出错（原因是m10.music.126.net被解析至127.0.0.1）
![image](https://user-images.githubusercontent.com/25716090/123762028-f640e500-d8f4-11eb-9511-6037bbb44fb3.png)

**Comment by injahow** [comment]
无法测试出相同情况，请提供歌曲id等具体信息

**Comment by kcn3388** [comment]
歌单id 450007071
实例地址：obsidian.kcn3388.club
kcn3388.com
全局海外ip的时候就报以上错误

**Comment by injahow** [comment]
![image](https://user-images.githubusercontent.com/42839062/123768217-b7ae2900-d8fa-11eb-9501-831cb86f59d1.png)
请尝试注释如图标记代码，请问使用http请求是否能够正常请求

**Comment by kcn3388** [comment]
> ![image](https://user-images.githubusercontent.com/42839062/123768217-b7ae2900-d8fa-11eb-9501-831cb86f59d1.png)
> 请尝试注释如图标记代码，请问使用http请求是否能够正常请求

经测试无效

**Comment by injahow** [comment]
`        case 'url':
            $m_url = json_decode($api->url($song->url_id, 320))->url;
            if ($m_url == '') {
                exit;
            }
            if ($m_url[4] != 's') {
                $m_url = str_replace('http', 'https', $m_url);
            }
            $m_url_arr = parse_url($m_url);
            if($m_url_arr['host'] == 'm10.music.126.net'){
                $m_url_arr['host'] = 'm8.music.126.net';
                $m_url_arr['scheme'] .= '://';
                $m_url = implode('', $m_url_arr);
            }
            header('Location: ' . $m_url);
            break;
`
目前只发现m10会出现CDN污染，请使用如上代码强制更换host，是否可以正常请求？

**Comment by injahow** [comment]
`......`
`if ($m_url[4] != 's') {`
`    $m_url = str_replace('http', 'https', $m_url);`
`}`
`$m_url_arr = parse_url($m_url);`
`if($m_url_arr['host'] == 'm10.music.126.net'){`
`    $m_url_arr['host'] = 'm8.music.126.net';`
`    $m_url_arr['scheme'] .= '://';`
`    $m_url = implode('', $m_url_arr);`
`}`
`header('Location: ' . $m_url);`
`......`
目前只发现m10会出现CDN污染，请使用如上代码强制更换host，是否可以正常请求？

**Comment by kcn3388** [comment]
> `if ($m_url[4] != 's') {`
> ` $m_url = str_replace('http', 'https', $m_url);`
> `}`
> `$m_url_arr = parse_url($m_url);`
> `if($m_url_arr['host'] == 'm10.music.126.net'){`
> ` $m_url_arr['host'] = 'm7.music.126.net';//海外ip未测试，可行性未知`
> ` $m_url_arr['scheme'] .= '://';`
> ` $m_url = implode('', $m_url_arr);`
> `}`
> `header('Location: ' . $m_url);`

m7海外可用国内不可用，改了以后是国内报403国外没问题

**Comment by kcn3388** [comment]
海外IP应该是彻底炸了，只要本机挂了全局梯子就不行了

**Comment by injahow** [comment]
> 海外IP应该是彻底炸了，只要本机挂了全局梯子就不行了

貌似没什么法，解析的地址就是不让海外IP播放
