### ISSUE TITLE
获取歌源，VIP音乐只能获取半分钟怎么办

### ISSUE THREAD

**Issue by vlssu** [injahow/meting-api#6]
获取歌源，VIP音乐只能获取半分钟怎么办
以前可以听到全部的，现在不知道怎么回事就不行了
是网易云本身问题吗？

**Comment by injahow** [comment]
> 获取歌源，VIP音乐只能获取半分钟怎么办
> 以前可以听到全部的，现在不知道怎么回事就不行了
> 是网易云本身问题吗？

可能是cookie已失效，请检查cookie参数

**Comment by vlssu** [comment]
谢谢，解决了，cookie忘记设置了
