### ISSUE TITLE
[Bug]使用后Aplayer无法正常显示网易云单曲

### ISSUE THREAD

**Issue by GrassBlock1** [injahow/meting-api#8]
如题 在不对 index_cn.php 进行任何修改的情况下，使用 [最新Release](https://github.com/injahow/meting-api/releases/tag/1.0) 的包无法正常显示出APlayer

自己尝试过修改所有 single 变量为 song ，但无解。

不知新的master是否解决了这个问题
（发个新Releases啊啊啊）

**Comment by injahow** [comment]
ok，因为之前一直懒得更新

**Comment by GrassBlock1** [comment]
> ok，因为之前一直懒得更新

谢谢，我去试试

**Comment by GrassBlock1** [comment]
> ok，因为之前一直懒得更新

![Screenshot_20211113104108](https://user-images.githubusercontent.com/46253950/141602843-ea55e3e7-617b-4a17-a77b-19ea3f6c2118.png)
So 是需要额外配置吗

**Comment by injahow** [comment]
> > ok，因为之前一直懒得更新
> 
> ![Screenshot_20211113104108](https://user-images.githubusercontent.com/46253950/141602843-ea55e3e7-617b-4a17-a77b-19ea3f6c2118.png)
> So 是需要额外配置吗

不需要配置，你使用方式的问题吗？

**Comment by GrassBlock1** [comment]
> > > ok，因为之前一直懒得更新
> > 
> > 
> > ![Screenshot_20211113104108](https://user-images.githubusercontent.com/46253950/141602843-ea55e3e7-617b-4a17-a77b-19ea3f6c2118.png)
> > So 是需要额外配置吗
> 
> 不需要配置，你使用方式的问题吗？

（（服务器问题，现在好了

不过似乎单曲问题仍未修复，未能显示在如图框选所示处
![Screenshot_20211113105657](https://user-images.githubusercontent.com/46253950/141603319-a6494e6d-6e08-4069-a0a7-82513e4c8494.png)

**Comment by injahow** [comment]
> > > > ok，因为之前一直懒得更新
> > > 
> > > 
> > > ![Screenshot_20211113104108](https://user-images.githubusercontent.com/46253950/141602843-ea55e3e7-617b-4a17-a77b-19ea3f6c2118.png)
> > > So 是需要额外配置吗
> > 
> > 
> > 不需要配置，你使用方式的问题吗？
> 
> （（服务器问题，现在好了
> 
> 不过似乎单曲问题仍未修复，未能显示在如图框选所示处 ![Screenshot_20211113105657](https://user-images.githubusercontent.com/46253950/141603319-a6494e6d-6e08-4069-a0a7-82513e4c8494.png)

这个好像是因为type名称不一致导致，js使用的'song'而api使用的'single'，你可以自己尝试修改或者等待下一个版本

**Comment by GrassBlock1** [comment]
> > > > > ok，因为之前一直懒得更新
> > > > 
> > > > 
> > > > ![Screenshot_20211113104108](https://user-images.githubusercontent.com/46253950/141602843-ea55e3e7-617b-4a17-a77b-19ea3f6c2118.png)
> > > > So 是需要额外配置吗
> > > 
> > > 
> > > 不需要配置，你使用方式的问题吗？
> > 
> > 
> > （（服务器问题，现在好了
> > 不过似乎单曲问题仍未修复，未能显示在如图框选所示处 ![Screenshot_20211113105657](https://user-images.githubusercontent.com/46253950/141603319-a6494e6d-6e08-4069-a0a7-82513e4c8494.png)
> 
> 这个好像是因为type名称不一致导致，js使用的'song'而api使用的'single'，你可以自己尝试修改或者等待下一个版本

好的。

**Comment by GrassBlock1** [comment]
期待修复。
